cacheFolder: ./.runtime/cache/yarn

deferredVersionFolder: ./.runtime/yarn/versions

installStatePath: ./.runtime/yarn/install-state.gz

nodeLinker: node-modules

patchFolder: ./.runtime/yarn/patches

pnpUnpluggedFolder: ./.runtime/yarn/unplugged

virtualFolder: ./.runtime/yarn/__virtual__
